import type { Product, Order, RevenueData, CategorySalesData } from './types';

// Dummy Products Data - Motorcycle Parts
export const products: Product[] = [
  {
    id: 'PRD001',
    name: 'Master Rem Brembo RCS 19',
    sku: 'BRM-RCS19',
    category: 'Rem',
    brand: 'Brembo',
    price: 4500000,
    stock: 12,
    status: 'aktif',
    image: '/products/brembo-rcs19.jpg',
    description: 'Master rem radial Brembo RCS 19 untuk performa pengereman maksimal',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'PRD002',
    name: 'Kaliper RCB S1 2 Piston',
    sku: 'RCB-S1-2P',
    category: 'Rem',
    brand: 'RCB',
    price: 850000,
    stock: 25,
    status: 'aktif',
    image: '/products/rcb-s1.jpg',
    description: 'Kaliper rem RCB S1 dengan 2 piston untuk motor matic',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-11-20'),
  },
  {
    id: 'PRD003',
    name: 'Baut Probolt Titanium M8x30',
    sku: 'PBT-TI-M8',
    category: 'Baut',
    brand: 'Probolt',
    price: 35000,
    stock: 150,
    status: 'aktif',
    image: '/products/probolt-ti.jpg',
    description: 'Baut titanium grade 5 untuk aplikasi racing',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: 'PRD004',
    name: 'Knalpot R9 Valencia Titan Series',
    sku: 'R9-VLC-TI',
    category: 'Knalpot',
    brand: 'R9',
    price: 2800000,
    stock: 8,
    status: 'aktif',
    image: '/products/r9-valencia.jpg',
    description: 'Knalpot racing R9 Valencia dengan material titanium',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-09-10'),
  },
  {
    id: 'PRD005',
    name: 'Swing Arm Daytona Aluminium',
    sku: 'DTN-SA-AL',
    category: 'Rangka',
    brand: 'Daytona',
    price: 3200000,
    stock: 5,
    status: 'aktif',
    image: '/products/daytona-swingarm.jpg',
    description: 'Swing arm aluminium CNC untuk motor sport',
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-08-25'),
  },
  {
    id: 'PRD006',
    name: 'CDI Racing BRT Dual Band',
    sku: 'BRT-CDI-DB',
    category: 'Elektrik',
    brand: 'BRT',
    price: 450000,
    stock: 3,
    status: 'aktif',
    image: '/products/brt-cdi.jpg',
    description: 'CDI programmable BRT dengan fitur dual band',
    createdAt: new Date('2024-05-08'),
    updatedAt: new Date('2024-07-30'),
  },
  {
    id: 'PRD007',
    name: 'Handgrip Domino XM2 Racing',
    sku: 'DMN-XM2',
    category: 'Aksesoris',
    brand: 'Domino',
    price: 280000,
    stock: 40,
    status: 'aktif',
    image: '/products/domino-xm2.jpg',
    description: 'Handgrip racing Domino XM2 dengan material karet premium',
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-11-05'),
  },
  {
    id: 'PRD008',
    name: 'Piston Kit Wiseco 66mm',
    sku: 'WSC-PK-66',
    category: 'Mesin',
    brand: 'Wiseco',
    price: 1800000,
    stock: 0,
    status: 'nonaktif',
    image: '/products/wiseco-piston.jpg',
    description: 'Piston forged Wiseco untuk bore up 66mm',
    createdAt: new Date('2024-02-28'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'PRD009',
    name: 'Shock Ohlins TTX GP',
    sku: 'OHL-TTX-GP',
    category: 'Suspensi',
    brand: 'Ohlins',
    price: 18500000,
    stock: 2,
    status: 'aktif',
    image: '/products/ohlins-ttx.jpg',
    description: 'Shock absorber Ohlins TTX GP untuk performa track day',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 'PRD010',
    name: 'Disc Brake Galfer Wave 320mm',
    sku: 'GLF-WV-320',
    category: 'Rem',
    brand: 'Galfer',
    price: 1250000,
    stock: 15,
    status: 'aktif',
    image: '/products/galfer-wave.jpg',
    description: 'Disc brake Galfer wave design untuk pendinginan optimal',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-09-15'),
  },
];

// Dummy Orders Data
export const orders: Order[] = [
  {
    id: 'ORD001',
    trackingId: 'NZR-2024120101',
    customerId: 'CUS001',
    customerName: 'Ahmad Rizky',
    customerEmail: 'ahmad.rizky@email.com',
    customerPhone: '081234567890',
    items: [
      { productId: 'PRD001', productName: 'Master Rem Brembo RCS 19', quantity: 1, price: 4500000 },
      { productId: 'PRD003', productName: 'Baut Probolt Titanium M8x30', quantity: 4, price: 35000 },
    ],
    total: 4640000,
    status: 'dikirim',
    shippingAddress: 'Jl. Sudirman No. 123, Jakarta Selatan',
    paymentMethod: 'Bank Transfer',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'ORD002',
    trackingId: 'NZR-2024120102',
    customerId: 'CUS002',
    customerName: 'Budi Santoso',
    customerEmail: 'budi.santoso@email.com',
    customerPhone: '082345678901',
    items: [
      { productId: 'PRD004', productName: 'Knalpot R9 Valencia Titan Series', quantity: 1, price: 2800000 },
    ],
    total: 2800000,
    status: 'menunggu_bayar',
    shippingAddress: 'Jl. Gatot Subroto No. 45, Bandung',
    paymentMethod: 'E-Wallet',
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'ORD003',
    trackingId: 'NZR-2024120103',
    customerId: 'CUS003',
    customerName: 'Dewi Lestari',
    customerEmail: 'dewi.lestari@email.com',
    customerPhone: '083456789012',
    items: [
      { productId: 'PRD002', productName: 'Kaliper RCB S1 2 Piston', quantity: 2, price: 850000 },
      { productId: 'PRD010', productName: 'Disc Brake Galfer Wave 320mm', quantity: 1, price: 1250000 },
    ],
    total: 2950000,
    status: 'diproses',
    shippingAddress: 'Jl. Ahmad Yani No. 78, Surabaya',
    paymentMethod: 'Credit Card',
    createdAt: new Date('2024-12-01'),
    updatedAt: new Date('2024-12-02'),
  },
  {
    id: 'ORD004',
    trackingId: 'NZR-2024113001',
    customerId: 'CUS004',
    customerName: 'Eko Prasetyo',
    customerEmail: 'eko.prasetyo@email.com',
    customerPhone: '084567890123',
    items: [
      { productId: 'PRD005', productName: 'Swing Arm Daytona Aluminium', quantity: 1, price: 3200000 },
    ],
    total: 3200000,
    status: 'selesai',
    shippingAddress: 'Jl. Diponegoro No. 56, Semarang',
    paymentMethod: 'Bank Transfer',
    createdAt: new Date('2024-11-30'),
    updatedAt: new Date('2024-12-01'),
  },
  {
    id: 'ORD005',
    trackingId: 'NZR-2024112901',
    customerId: 'CUS005',
    customerName: 'Fitri Handayani',
    customerEmail: 'fitri.h@email.com',
    customerPhone: '085678901234',
    items: [
      { productId: 'PRD006', productName: 'CDI Racing BRT Dual Band', quantity: 1, price: 450000 },
      { productId: 'PRD007', productName: 'Handgrip Domino XM2 Racing', quantity: 1, price: 280000 },
    ],
    total: 730000,
    status: 'batal',
    shippingAddress: 'Jl. Pahlawan No. 12, Yogyakarta',
    paymentMethod: 'COD',
    createdAt: new Date('2024-11-29'),
    updatedAt: new Date('2024-11-30'),
  },
  {
    id: 'ORD006',
    trackingId: 'NZR-2024120201',
    customerId: 'CUS006',
    customerName: 'Gunawan Wijaya',
    customerEmail: 'gunawan.w@email.com',
    customerPhone: '086789012345',
    items: [
      { productId: 'PRD009', productName: 'Shock Ohlins TTX GP', quantity: 1, price: 18500000 },
    ],
    total: 18500000,
    status: 'diproses',
    shippingAddress: 'Jl. Merdeka No. 99, Medan',
    paymentMethod: 'Bank Transfer',
    createdAt: new Date('2024-12-02'),
    updatedAt: new Date('2024-12-02'),
  },
];

// Monthly Revenue Data for Bar Chart
export const revenueData: RevenueData[] = [
  { month: 'Jan', revenue: 32000000 },
  { month: 'Feb', revenue: 28000000 },
  { month: 'Mar', revenue: 35000000 },
  { month: 'Apr', revenue: 42000000 },
  { month: 'Mei', revenue: 38000000 },
  { month: 'Jun', revenue: 45000000 },
  { month: 'Jul', revenue: 52000000 },
  { month: 'Agu', revenue: 48000000 },
  { month: 'Sep', revenue: 55000000 },
  { month: 'Okt', revenue: 58000000 },
  { month: 'Nov', revenue: 62000000 },
  { month: 'Des', revenue: 45000000 },
];

// Category Sales Data for Pie Chart
export const categorySalesData: CategorySalesData[] = [
  { category: 'Rem', sales: 40, fill: 'var(--chart-1)' },
  { category: 'Baut', sales: 25, fill: 'var(--chart-2)' },
  { category: 'Knalpot', sales: 18, fill: 'var(--chart-3)' },
  { category: 'Lainnya', sales: 17, fill: 'var(--chart-4)' },
];

// Helper function to format currency in Indonesian Rupiah
export function formatRupiah(amount: number): string {
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

// Helper function to format date in Indonesian
export function formatDate(date: Date): string {
  return new Intl.DateTimeFormat('id-ID', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  }).format(date);
}

// Get low stock products (stock <= 5)
export function getLowStockProducts(): Product[] {
  return products.filter(p => p.stock <= 5 && p.status === 'aktif');
}

// Dashboard metrics
export const dashboardMetrics = {
  totalRevenue: 45000000,
  revenueChange: '+15%',
  newOrders: 120,
  ordersChange: '+5%',
  productsSold: 350,
  lowStockCount: getLowStockProducts().length,
};
